version: '3'


services:
  nginx:
    image: nginx:stable-alpine
    #container_name: nginx
    ports:
     - "8081:80"
     
    volumes:
      - ./src:/var/www/html
      - ./vue/dist:/var/www/frontend
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
     - laravel
  mysql:
    image: mysql:8
    #container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: elearning
       MYSQL_USER: islem
       MYSQL_PASSWORD: 28225822
       MYSQL_ROOT_PASSWORD: 28225822
       SERVICE_TAGS: dev
       #SERVICE_NAME: mysql

    networks:
      - laravel

  myapp-websockets:
    build:
     context: .
     dockerfile: Dockerfile
     args:
        - PUID=${HOST_PUID}
        - PGID=${HOST_PGID}
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    # dockerfile: DockerFile
    command: ['php', 'artisan', 'websockets:serve']
    container_name: myapp-websockets
    restart: unless-stopped
   
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "6001:6001"
    networks:
      - laravel
  redis:
    build: ./redis
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel
  php:
    build:
     context: .
     dockerfile: Dockerfile
     args:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    
    volumes:
      - ./src:/var/www/html
    #command: ['php', 'artisan', 'serve','--host','0.0.0.0:9000']  
    ports:
      - "9000:9000" 


    networks:
      - laravel  

  # front:
  #   build:
  #     context: ./vue
      
   
  #   volumes:
  #      - ./vue:/app
  #   ports:
  #     - "8000:8000" 
    
  #   networks:
  #     - laravel  




volumes:
  mysql:
networks:
    laravel:
