version: '3'


services:
  nginx:
    build:
     context: .
     dockerfile: ./nginx/Dockerfile
 
    ports:
     - "8081:80"
     - "6002:6002"
     - "81:81"
     

    depends_on:
      - php
      - mysql
      - myapp-websockets

    networks:
     - laravel
  mysql:
    image: mysql:8
   
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: elearning
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       SERVICE_TAGS: dev
 

    networks:
      - laravel

  myapp-websockets:
   
    image: myphp
   
    command: ['php', 'artisan', 'websockets:serve']
    container_name: myapp-websockets
    restart: unless-stopped
    # volumes:
    #   - .env.prod:/var/www/html/.env
   
   
    ports:
      - "6001:6001"
    networks:
      - laravel
    depends_on:
      - php
      
  redis:
    build: ./redis
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel
  php:
    image: myphp
    
    build:
     context: .
     target: production
     dockerfile: Dockerfile
     args:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - USERNAME=${CONTAINER_USERNAME}
    
    volumes:
      - .env.prod:/var/www/html/.env
    ports:
      - "9000:9000" 
   

   
    networks:
      - laravel  

  front:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   
    networks:
      - laravel    
   
   
  supervisor:
    image: myphp 
    container_name: supervisor
    restart: unless-stopped
    networks:
      - laravel
    command: "/usr/bin/supervisord -n -c  /etc/supervisor/conf.d/laravel-worker.conf" 
    depends_on:
      - php
      
  
       
     
    
     




volumes:
  mysql:

networks:
    laravel:
