version: '3'


services:
  nginx:
    image: nginx:stable-alpine
    #container_name: nginx
    ports:
     - "8081:80"
     
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
     - laravel
  mysql:
    image: mysql:8
    #container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: elearning
       MYSQL_USER: islem
       MYSQL_PASSWORD: 28225822
       MYSQL_ROOT_PASSWORD: 28225822
       SERVICE_TAGS: dev
       #SERVICE_NAME: mysql

    networks:
      - laravel

  # myapp-websockets:
  #   build:
  #    context: ./websockets
  #    args:
  #       - PUID=${HOST_PUID}
  #       - PGID=${HOST_PGID}
  #       - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
  #   # dockerfile: DockerFile
  #   command: ['php', 'artisan', 'websockets:serve']
  #   container_name: myapp-websockets
  #   restart: unless-stopped
   
  #   volumes:
  #     - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
  #   ports:
  #     - "6001:6001"
  #   networks:
  #     - laravel
    
  php:
    build:
     context: .
     dockerfile: DockerFile
    
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000" 
     
     

    networks:
      - laravel  





volumes:
  mysql:
networks:
    laravel:
